version: '3.8'

services:
  bot-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["python", "./bot.py"]
    volumes:
      - /root/cu-org-bot/main.db:/app/main.db
